# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch (usually 'main')
  push:
    branches:
      - main

  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  # Build and Deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can use any supported Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev
          npx gh-pages -d build

# This workflow will build the React app and deploy it to GitHub Pages
# whenever you push to the 'main' branch. You can also trigger the deployment manually
# from the GitHub Actions tab.

